# SPDX-License-Identifier: MIT
version: '2'

includes:
  local: ./tasks/BuildTasks.yml
  docker: ./tasks/DockerTasks.yml
  globalVars: ./Taskvars.yml

tasks:
  deploy-secrets:
    desc: Deploy secrets
    cmds:
    - |
      kubectl --context={{.KUBE_CONTEXT}} config view --raw --minify=true --flatten=true | \
      sed 's#server:.*#server: https://kubernetes.default.svc#g' > config
    - |
      kubectl --context={{.KUBE_CONTEXT}} --namespace={{.NAMESPACE}} create secret generic kube-config --from-file=config --dry-run --output=yaml | \
      kubectl --context={{.KUBE_CONTEXT}} --namespace {{.NAMESPACE}} apply -f -
    - rm config

  deploy-local:
    desc: Deploy namespace-provisioner
    cmds:
    - kubectl --context={{.KUBE_CONTEXT}} --namespace={{.NAMESPACE}} delete --filename=deploy/namespace-provisioner-{{.KUBE_CONTEXT}}.yaml --ignore-not-found
    - kubectl --context={{.KUBE_CONTEXT}} --namespace={{.NAMESPACE}} apply --filename=deploy/namespace-provisioner-{{.KUBE_CONTEXT}}.yaml
