# SPDX-License-Identifier: MIT
name: Licensed

on:
  push:
    branches:
    - poc/github-actions/disabled

jobs:
  test:
    runs-on: ubuntu-18.04
    name: Check licenses
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
    - name: Set up task
      env:
        TASK_VERSION: 2.6.0
      run: |
        sudo bash -c "curl -sL https://taskfile.dev/install.sh | bash -s -- -b /usr/local/bin v${TASK_VERSION}"
    - name: Set up Licensed
      env:
        LICENSED_VERSION: 2.11.1
      run: |-
        curl -sLSfo /tmp/licensed.tgz "https://github.com/github/licensed/releases/download/${LICENSED_VERSION}/licensed-${LICENSED_VERSION}-linux-x64.tar.gz"
        mkdir -p /tmp/licensed
        tar xvf /tmp/licensed.tgz -C /tmp/licensed
        sudo mv /tmp/licensed/licensed /usr/local/bin/licensed
        rm -rf /tmp/licensed*
    - name: Checkout
      uses: actions/checkout@v2
    - name: License check
      run: |-
        task local:prepare
        licensed status
