# SPDX-License-Identifier: MIT

name: Release

on:
  push:
    tags:
    - '*.*.*'

jobs:
  release-build:
    runs-on: ubuntu-18.04
    env:
      DOCKER_REGISTRY: docker.pkg.github.com/${{github.repository}}
    steps:
    - name: Set up task
      env:
        TASK_VERSION: 2.7.1
      run: |
        sudo bash -c "curl -sLSf https://taskfile.dev/install.sh | bash -s -- -b /usr/local/bin v${TASK_VERSION}"
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: |
        DOCKER_REGISTRY="${DOCKER_REGISTRY}" task docker:build
    - name: Test
      run: |
        task docker:test
    - name: Push image
      run: |
        DOCKER_REGISTRY="${DOCKER_REGISTRY}" task docker:push-release DOCKER_USERNAME=anonymous DOCKER_PASSWORD=${{secrets.GITHUB_TOKEN}}
    - name: Create release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        tag_name: ${{github.ref}}
        release_name: ${{github.ref}}
        draft: true
        prerelease: false
