# SPDX-License-Identifier: MIT
name: Static analysis

on:
  push:
    branches:
    - poc/github-actions/disabled

jobs:
  link-checker:
    name: markdown-link-checker
    strategy:
      matrix:
        os: [ubuntu-18.04]
        go: [1.13]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run action
      uses: ./.github/actions/markdown-link-checker
